### ISSUE TITLE
Show report to user

### ISSUE THREAD

**Issue by alexWyllie** [alexWyllie/CS498-Group-1#2]
Priority: 1
Story points: 2
Needs to be able to show the differences to the User.

**Comment by alexWyllie** [comment]
Implement through Jelly attached to OutputAction.

**Comment by alexWyllie** [comment]
Currently looks horrible. My perfectly formatted plaintext output from the backend just gets shoved onto a single line on a page in the build. However, it looks fine on the console.

**Comment by CharlesMaroudas** [comment]
Report of newly passing, newly failing, and still failing tests all show to user in the main panel view of Jenkins plugin.
